#portFile: input
portFile="/tmp/portPs"

maxCocurrent=5
#unit: ms
timeout=9000

# targetURL="http://ifconfig.me"
targetURL="https://raw.githubusercontent.com/sunliang711/fastest/master/10m"

#resultFile: output
resultFile="/tmp/fastestPort.result"

[log]
level="info"
# logfile="/tmp/fastestPort.log"
logfile=""
showFullTime=true
reportCaller=false
