portFile="/tmp/portPs"
maxCocurrent=5
#unit: ms
timeout=9000
targetURL="http://ifconfig.me"
resultFile="/tmp/fastestPort.result"
[log]
level="debug"
logfile="/tmp/fastestPort.log"
showFullTime=true
reportCaller=false
